[package]
name = "mine-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.2"
serde = {version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
uuid = "1.10.0"
